[features]
seeds = false
skip-lint = false
[programs.localnet]
storage_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
storage = "Tg6PaFpoGXkYsidMpWTK62BeZ7FEfcYkg476zPFsLnT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ongrid/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
